### ISSUE TITLE
Could not load NIB in bundle

### ISSUE THREAD

**Issue by jkyeo** [xmartlabs/Xniffer#3]
Nice framework! But when using it via pod. Crashed. It reported that:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/<UserName>/Library/Developer/CoreSimulator/Devices/D7ED7C3A-3933-4F70-B951-CD5446737CF3/data/Containers/Bundle/Application/CB81BB7A-2841-4C0E-ABFA-E540034A183C/pangu.app/Frameworks/Xniffer.framework> (loaded)' with name 'ResultCell''

**Comment by mcousillas6** [comment]
Hey!

I've just fixed the issue. version 1.0.2 should be working Ok. 
Let me know if it works for you.

**Comment by jkyeo** [comment]
@mcousillas6 Yes, v1.0.2 works for me. Thanks a lot.
