### ISSUE TITLE
[Question] how do you use mode: .custom?

### ISSUE THREAD

**Issue by RolandasRazma** [xmartlabs/Xniffer#5]
how do you use mode: .custom? I see no way of using my own XnifferDelegate

**Comment by mcousillas6** [comment]
Hey,

There was an issue with the access level of the shared instance and the delegate (both should have been public from the start). This prevented you to be able to set the delegate inside the callback on the `.custom` mode. 
Version `1.0.3` should work fine.

Thank you for reporting the issue, hope the new fix works for you.
